/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    articles: Article;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    navigation: Navigation;
    footer: Footer;
    'home-page': HomePage;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Display name shown as article author when populated.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  /**
   * URL segment. Auto-fills from title when empty.
   */
  slug: string;
  excerpt: string;
  category:
    'Pricing' | 'Contract Negotiation' | 'Site Selection' | 'AI Infrastructure' | 'Cost Optimization' | 'Procurement';
  kind: 'article' | 'tip';
  featured?: boolean | null;
  readTime: string;
  publishedAt: string;
  /**
   * Illustration used on cards when no thumbnail is set.
   */
  imageVariant: 'server-room' | 'exterior' | 'cooling-aisle';
  imageAlt: string;
  /**
   * Optional header image. Falls back to illustration variant.
   */
  thumbnail?: (number | null) | Media;
  sections: {
    heading?: string | null;
    paragraphs: {
      text: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  kind?: T;
  featured?: T;
  readTime?: T;
  publishedAt?: T;
  imageVariant?: T;
  imageAlt?: T;
  thumbnail?: T;
  sections?:
    | T
    | {
        heading?: T;
        paragraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  /**
   * Primary header nav items (desktop + mobile).
   */
  links: {
    label: string;
    href: string;
    id?: string | null;
  }[];
  /**
   * Opens the quote / sourcing modal.
   */
  primaryCtaLabel: string;
  secondaryCtaLabel: string;
  secondaryCtaHref: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline: string;
  columns: {
    title: string;
    links: {
      label: string;
      href: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  /**
   * Use {year} for the current year.
   */
  copyrightTemplate: string;
  legalLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero: {
    eyebrow: string;
    headline: string;
    body: string;
    ctaLabel: string;
  };
  stats: {
    eyebrow: string;
    items: {
      value: string;
      label: string;
      id?: string | null;
    }[];
  };
  services: {
    eyebrow: string;
    headline: string;
    body: string;
    ctaLabel: string;
    items: {
      /**
       * Stable id, e.g. footprint
       */
      key: string;
      name: string;
      tagline: string;
      icon: 'server' | 'cloud' | 'network' | 'shield' | 'cpu' | 'globe';
      bestFor: string;
      weHelpWith: string;
      deployTime: string;
      features: {
        text: string;
        id?: string | null;
      }[];
      id?: string | null;
    }[];
  };
  globalNetwork: {
    eyebrow: string;
    headline: string;
    body: string;
    ctaLabel: string;
  };
  testimonials: {
    eyebrow: string;
    headline: string;
    body: string;
    items: {
      quote: string;
      name: string;
      role: string;
      company: string;
      id?: string | null;
    }[];
  };
  team: {
    eyebrow: string;
    headline: string;
    body: string;
    ctaLabel: string;
    members: {
      key: string;
      name: string;
      role: string;
      /**
       * Public path, e.g. /placeholder-images/people/brad-mclaughlin.jpg
       */
      imagePath: string;
      id?: string | null;
    }[];
  };
  intake: {
    eyebrow: string;
    headline: string;
    body: string;
    benefits: {
      text: string;
      id?: string | null;
    }[];
    steps: {
      text: string;
      id?: string | null;
    }[];
    needOptions: {
      text: string;
      id?: string | null;
    }[];
    regionOptions: {
      text: string;
      id?: string | null;
    }[];
    footprintOptions: {
      text: string;
      id?: string | null;
    }[];
    timelineOptions: {
      text: string;
      id?: string | null;
    }[];
  };
  blogSection: {
    eyebrow: string;
    headline: string;
    body: string;
    browseAllLabel: string;
    expertInsights?:
      | {
          quote: string;
          name: string;
          role: string;
          focus: string;
          id?: string | null;
        }[]
      | null;
    expertEyebrow: string;
    expertHeadline: string;
    bottomCta: {
      eyebrow: string;
      headline: string;
      body: string;
      ctaLabel: string;
    };
    featuredReport: {
      eyebrow: string;
      title: string;
      description: string;
      pages: string;
      format: string;
      audience: string;
      ctaLabel: string;
      highlights: {
        text: string;
        id?: string | null;
      }[];
    };
  };
  faq: {
    eyebrow: string;
    headline: string;
    body: string;
    items: {
      question: string;
      answer: string;
      id?: string | null;
    }[];
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  secondaryCtaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  copyrightTemplate?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        ctaLabel?: T;
      };
  stats?:
    | T
    | {
        eyebrow?: T;
        items?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  services?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        ctaLabel?: T;
        items?:
          | T
          | {
              key?: T;
              name?: T;
              tagline?: T;
              icon?: T;
              bestFor?: T;
              weHelpWith?: T;
              deployTime?: T;
              features?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  globalNetwork?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        ctaLabel?: T;
      };
  testimonials?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        items?:
          | T
          | {
              quote?: T;
              name?: T;
              role?: T;
              company?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        ctaLabel?: T;
        members?:
          | T
          | {
              key?: T;
              name?: T;
              role?: T;
              imagePath?: T;
              id?: T;
            };
      };
  intake?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
        steps?:
          | T
          | {
              text?: T;
              id?: T;
            };
        needOptions?:
          | T
          | {
              text?: T;
              id?: T;
            };
        regionOptions?:
          | T
          | {
              text?: T;
              id?: T;
            };
        footprintOptions?:
          | T
          | {
              text?: T;
              id?: T;
            };
        timelineOptions?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  blogSection?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        browseAllLabel?: T;
        expertInsights?:
          | T
          | {
              quote?: T;
              name?: T;
              role?: T;
              focus?: T;
              id?: T;
            };
        expertEyebrow?: T;
        expertHeadline?: T;
        bottomCta?:
          | T
          | {
              eyebrow?: T;
              headline?: T;
              body?: T;
              ctaLabel?: T;
            };
        featuredReport?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              pages?: T;
              format?: T;
              audience?: T;
              ctaLabel?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
            };
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        headline?: T;
        body?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}